language: node_js
node_js:
- '7.0'
env:
  global:
  - SAUCE_USERNAME=sauce_examples
addons:
  jwt:
    secure: aVz3Ma2vXC/jY98E5shBuiPE6SR/8SrrLGS4xaxVXh7nsIp03njlGueflPxmZmpgxSYjwGBsWKPwkzi9XjrFqLItti6hcEoe/M7KOL+cYDb/1/4hurHKg4TG3bkOLfr6qKiHbRC+sn/wVfdw4Axfw7slqeFeYD7NVFseuE5GJ7yiRB9My+BTmTsfqS7RHZdWXWxNyA0OmDjoa9XmgdMmd1OL5hn4uk42VYsZgY/zvg2BSFszlNWi9nezySzIwbFJUp1AIOIYNm0+fm8NqWrTA8qX00C1d88jFs18CAaWBSwJvy6bhsDxMKMXEY3E1crr2PhzfkYeI2Ft060qLnuyu0egCk28SACDckBQJmTm2PghtT+NxaSBioWQzFVYAEi0WqIdTPulxGhWiMbhhQLypjBjelhVStyP0BfiXzMzf5v1H5BsLUUZPbJ3Z0ryWFgR1JbqfZzwj0SnpRmz3QIeKyolQPJywgAC0iRdMhpcv4i5vhDNMX1cmu0P5NmXy9ZzwMgzTUyDVf6e/Lu+F8WtMjQA8HAe3SknyD3LGpQqPbULmr4ouP+E2T5cROuVO7r9+xTf+/76BteSMWu25wFGC57jkVas8IizceM+B7iv0CYLGNsB0bGSyWch6GUQiSIzgR/DgtqWo25ZCscP+f6jKUqDu2dd2N107WMEBdevG3o=
